/* eslint-disable */
// AUTO-GENERATED FILE — DO NOT EDIT.
// Regenerate with: pnpm --filter @northskysocial/stratos-client lexgen
// Source: lexicons/zone/stratos/**/*.json

import type { LexiconDoc } from '@atproto/lexicon'

export const stratosLexicons: LexiconDoc[] = [
{
  "lexicon": 1,
  "id": "zone.stratos.actor.enrollment",
  "defs": {
    "main": {
      "type": "record",
      "description": "A record indicating the user is enrolled in a Stratos service. Published to the user's PDS during OAuth enrollment for endpoint discovery by AppViews. Multiple enrollment records are supported — one per Stratos service.",
      "key": "any",
      "record": {
        "type": "object",
        "required": ["service", "signingKey", "attestation", "createdAt"],
        "properties": {
          "service": {
            "type": "string",
            "format": "uri",
            "description": "The Stratos service endpoint URL where this user's private data is stored."
          },
          "boundaries": {
            "type": "array",
            "description": "Service-qualified boundaries the user has access to on this Stratos service, each in '{serviceDid}/{domainName}' format.",
            "items": {
              "type": "ref",
              "ref": "zone.stratos.boundary.defs#Domain"
            },
            "maxLength": 50
          },
          "signingKey": {
            "type": "string",
            "description": "The user's P-256 public key as a did:key string, generated by the Stratos service for user-level record signing."
          },
          "attestation": {
            "type": "ref",
            "ref": "#serviceAttestation",
            "description": "Service attestation vouching for the user's enrollment, boundaries, and signing key."
          },
          "createdAt": {
            "type": "string",
            "format": "datetime",
            "description": "Timestamp when the enrollment was created."
          }
        }
      }
    },
    "serviceAttestation": {
      "type": "object",
      "description": "An attestation signed by the Stratos service key. The signed payload is DAG-CBOR encoded {boundaries, did, signingKey} with sorted keys.",
      "required": ["sig", "signingKey"],
      "properties": {
        "sig": {
          "type": "bytes",
          "description": "Raw signature bytes of the DAG-CBOR encoded attestation payload, signed by the service key."
        },
        "signingKey": {
          "type": "string",
          "description": "The Stratos service's public key as a did:key string, used to verify the attestation signature."
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.admin.addAdmin",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Grant admin access to a DID. Requires admin authorization.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did"],
          "properties": {
            "did": {
              "type": "string",
              "format": "did",
              "description": "The DID to grant admin access to."
            }
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did"],
          "properties": {
            "did": { "type": "string", "format": "did" }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.admin.listAdmins",
  "defs": {
    "main": {
      "type": "query",
      "description": "List everyone holding admin access. Requires admin authorization.",
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["admins", "viewer"],
          "properties": {
            "admins": {
              "type": "array",
              "items": { "type": "ref", "ref": "#admin" }
            },
            "viewer": {
              "type": "string",
              "format": "did",
              "description": "The DID of the requesting admin."
            }
          }
        }
      }
    },
    "admin": {
      "type": "object",
      "required": ["did", "source"],
      "properties": {
        "did": { "type": "string", "format": "did" },
        "source": {
          "type": "string",
          "description": "Where the grant comes from. Config admins cannot be revoked through the API.",
          "knownValues": ["config", "database"]
        },
        "addedAt": {
          "type": "string",
          "format": "datetime",
          "description": "When access was granted. Absent for config admins."
        },
        "addedBy": {
          "type": "string",
          "format": "did",
          "description": "Who granted access. Absent for config admins."
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.admin.listEnrollments",
  "defs": {
    "main": {
      "type": "query",
      "description": "List enrollments in this Stratos service. Requires admin authorization.",
      "parameters": {
        "type": "params",
        "properties": {
          "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 100,
            "default": 50,
            "description": "Maximum number of enrollments to return."
          },
          "cursor": {
            "type": "string",
            "description": "Pagination cursor from a previous response."
          },
          "boundary": {
            "type": "string",
            "description": "Only return members holding this boundary."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["enrollments"],
          "properties": {
            "enrollments": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "#enrollment"
              }
            },
            "cursor": {
              "type": "string",
              "description": "Cursor for the next page. Absent on the last page."
            },
            "total": {
              "type": "integer",
              "description": "Total number of enrollments in the service. Absent when a boundary filter is applied."
            }
          }
        }
      }
    },
    "enrollment": {
      "type": "object",
      "required": ["did", "enrolledAt", "active", "boundaries"],
      "properties": {
        "did": {
          "type": "string",
          "format": "did",
          "description": "The enrolled DID."
        },
        "enrolledAt": {
          "type": "string",
          "format": "datetime",
          "description": "When the DID was enrolled."
        },
        "active": {
          "type": "boolean",
          "description": "Whether the enrollment is currently active."
        },
        "isService": {
          "type": "boolean",
          "description": "Whether this is a service enrollment rather than a user."
        },
        "boundaries": {
          "type": "array",
          "items": {
            "type": "ref",
            "ref": "zone.stratos.boundary.defs#Domain"
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.admin.removeAdmin",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Revoke admin access from a DID. Config-provided admins cannot be revoked here, and an admin cannot revoke their own access.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did"],
          "properties": {
            "did": {
              "type": "string",
              "format": "did",
              "description": "The DID to revoke admin access from."
            }
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did"],
          "properties": {
            "did": { "type": "string", "format": "did" }
          }
        }
      },
      "errors": [
        {
          "name": "NotFound",
          "description": "The DID does not hold admin access."
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.admin.setActive",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Activate or deactivate an enrolled member. Requires admin authorization. Deactivation is reversible and preserves the member's boundaries.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did", "active"],
          "properties": {
            "did": {
              "type": "string",
              "format": "did",
              "description": "The member to update."
            },
            "active": {
              "type": "boolean",
              "description": "Whether the member's enrollment should be active."
            }
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did", "active"],
          "properties": {
            "did": { "type": "string", "format": "did" },
            "active": { "type": "boolean" }
          }
        }
      },
      "errors": [
        { "name": "NotFound", "description": "The DID is not enrolled." }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.boundary.defs",
  "defs": {
    "Domain": {
      "type": "object",
      "description": "A specific domain to define exposure boundary.",
      "required": ["value"],
      "properties": {
        "value": {
          "type": "string",
          "description": "Service-qualified boundary identifier in the format '{serviceDid}/{domainName}', e.g. 'did:web:stratos.example.com/engineering'.",
          "maxLength": 253
        }
      }
    },
    "Domains": {
      "type": "object",
      "description": "A collection of domains that define the exposure boundary for a record.",
      "required": ["values"],
      "properties": {
        "values": {
          "type": "array",
          "description": "The single domain that can access this record. Exactly one domain per record (one record, one space); the array shape is retained for wire compatibility.",
          "items": { "type": "ref", "ref": "#Domain" },
          "minLength": 1,
          "maxLength": 1
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.defs",
  "defs": {
    "source": {
      "type": "object",
      "description": "Indicates this record requires hydration from an external service. The stub record on the PDS contains minimal data; full content is fetched from the service endpoint.",
      "required": ["vary", "subject", "service"],
      "properties": {
        "vary": {
          "type": "string",
          "description": "Indicates when hydration is needed. 'authenticated' means full content requires viewer authentication.",
          "knownValues": ["authenticated", "unauthenticated"],
          "maxLength": 128
        },
        "subject": {
          "type": "ref",
          "ref": "#subjectRef",
          "description": "Reference to the full record at the hydration service."
        },
        "service": {
          "type": "string",
          "format": "did",
          "description": "DID of the hydration service, optionally with fragment identifying the service entry (e.g., 'did:plc:abc123#atproto_pns')."
        }
      }
    },
    "subjectRef": {
      "type": "object",
      "description": "A strong reference to a record, including its content hash for verification.",
      "required": ["uri", "cid"],
      "properties": {
        "uri": {
          "type": "string",
          "format": "at-uri",
          "description": "AT-URI of the record at the hydration service."
        },
        "cid": {
          "type": "string",
          "format": "cid",
          "description": "CID of the full record content for integrity verification."
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.embed.images",
  "defs": {
    "main": {
      "type": "object",
      "description": "A set of images embedded in a Stratos post. Similar to app.bsky.embed.images but for private data.",
      "required": ["images"],
      "properties": {
        "images": {
          "type": "array",
          "items": { "type": "ref", "ref": "#image" },
          "maxLength": 4
        }
      }
    },
    "image": {
      "type": "object",
      "required": ["image", "alt"],
      "properties": {
        "image": { "type": "blob", "description": "The image blob." },
        "alt": {
          "type": "string",
          "description": "Alternative text for the image, for accessibility."
        },
        "aspectRatio": { "type": "ref", "ref": "#aspectRatio" }
      }
    },
    "aspectRatio": {
      "type": "object",
      "required": ["width", "height"],
      "properties": {
        "width": { "type": "integer" },
        "height": { "type": "integer" }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.enrollment.status",
  "defs": {
    "main": {
      "type": "query",
      "description": "Check enrollment status for a DID in this Stratos service.",
      "parameters": {
        "type": "params",
        "required": ["did"],
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID to check enrollment for."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did", "enrolled"],
          "properties": {
            "did": {
              "type": "string",
              "format": "did",
              "description": "The DID that was checked."
            },
            "enrolled": {
              "type": "boolean",
              "description": "Whether the DID is enrolled in this Stratos service."
            },
            "enrolledAt": {
              "type": "string",
              "format": "datetime",
              "description": "When the DID was enrolled, if enrolled."
            },
            "boundaries": {
              "type": "array",
              "description": "Authoritative boundaries assigned. Only included when request is authenticated.",
              "items": {
                "type": "ref",
                "ref": "zone.stratos.boundary.defs#Domain"
              }
            }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.enrollment.unenroll",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Unenroll from the Stratos service, revoking the session and deleting the enrollment record from the user's PDS.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "properties": {}
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "properties": {
            "success": {
              "type": "boolean"
            }
          }
        }
      },
      "errors": [{ "name": "NotEnrolled" }, { "name": "AuthRequired" }]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.feed.getTimeline",
  "defs": {
    "main": {
      "type": "query",
      "description": "Fetch a timeline of posts.",
      "parameters": {
        "type": "params",
        "properties": {
          "limit": {
            "type": "integer",
            "default": 50,
            "minimum": 1,
            "maximum": 100
          },
          "cursor": {
            "type": "string"
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["feed"],
          "properties": {
            "feed": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.feed.defs#feedViewPost"
              }
            },
            "cursor": {
              "type": "string"
            }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.feed.post",
  "defs": {
    "main": {
      "type": "record",
      "description": "Record containing a private Stratos post with domain boundary restrictions. When stored on user's PDS as a stub, only 'source' and 'createdAt' are present. Full content is available from the hydration service.",
      "key": "tid",
      "record": {
        "type": "object",
        "required": ["createdAt"],
        "properties": {
          "source": {
            "type": "ref",
            "ref": "zone.stratos.defs#source",
            "description": "When present, indicates this is a stub record. Full content should be hydrated from the referenced service."
          },
          "text": {
            "type": "string",
            "maxLength": 3000,
            "maxGraphemes": 300,
            "description": "The primary post content. May be an empty string, if there are embeds. Omitted in stub records."
          },
          "boundary": {
            "type": "union",
            "description": "Limit exposure to defined domains. Omitted in stub records.",
            "refs": ["zone.stratos.boundary.defs#Domains"]
          },
          "facets": {
            "type": "array",
            "description": "Annotations of text (mentions, URLs, hashtags, etc)",
            "items": { "type": "ref", "ref": "app.bsky.richtext.facet" }
          },
          "reply": { "type": "ref", "ref": "#replyRef" },
          "embed": {
            "type": "union",
            "refs": [
              "zone.stratos.embed.images",
              "app.bsky.embed.images",
              "app.bsky.embed.video",
              "app.bsky.embed.external",
              "app.bsky.embed.record",
              "app.bsky.embed.recordWithMedia"
            ]
          },
          "langs": {
            "type": "array",
            "description": "Indicates human language of post primary text content.",
            "maxLength": 3,
            "items": { "type": "string", "format": "language" }
          },
          "labels": {
            "type": "union",
            "description": "Self-label values for this post. Effectively content warnings.",
            "refs": ["com.atproto.label.defs#selfLabels"]
          },
          "tags": {
            "type": "array",
            "description": "Additional hashtags, in addition to any included in post text and facets.",
            "maxLength": 8,
            "items": { "type": "string", "maxLength": 640, "maxGraphemes": 64 }
          },
          "createdAt": {
            "type": "string",
            "format": "datetime",
            "description": "Client-declared timestamp when this post was originally created."
          }
        }
      }
    },
    "replyRef": {
      "type": "object",
      "description": "Reference to parent and root posts for replies. Must reference stratos posts only.",
      "required": ["root", "parent"],
      "properties": {
        "root": { "type": "ref", "ref": "com.atproto.repo.strongRef" },
        "parent": { "type": "ref", "ref": "com.atproto.repo.strongRef" }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.feedgen.describeFeed",
  "defs": {
    "main": {
      "type": "query",
      "description": "List feeds offered by this generator.",
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did", "feeds"],
          "properties": {
            "did": { "type": "string", "format": "did" },
            "feeds": {
              "type": "array",
              "items": { "type": "ref", "ref": "#feedDescription" }
            }
          }
        }
      }
    },
    "feedDescription": {
      "type": "object",
      "required": ["id", "boundary"],
      "properties": {
        "id": { "type": "string" },
        "boundary": { "type": "string" },
        "displayName": { "type": "string" },
        "description": { "type": "string" }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.feedgen.getFeed",
  "defs": {
    "main": {
      "type": "query",
      "description": "Fetch a boundary-scoped hydrated feed. Requires service-auth.",
      "parameters": {
        "type": "params",
        "required": ["feed"],
        "properties": {
          "feed": { "type": "string", "description": "Configured feed id." },
          "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 100,
            "default": 50
          },
          "cursor": { "type": "string" }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["feed"],
          "properties": {
            "cursor": { "type": "string" },
            "feed": {
              "type": "array",
              "items": { "type": "ref", "ref": "#feedViewPost" }
            }
          }
        }
      },
      "errors": [{ "name": "UnknownFeed" }, { "name": "BoundaryMismatch" }]
    },
    "feedViewPost": {
      "type": "object",
      "required": ["post"],
      "properties": {
        "post": { "type": "ref", "ref": "#postView" }
      }
    },
    "postView": {
      "type": "object",
      "required": ["uri", "cid", "author", "record", "indexedAt"],
      "properties": {
        "uri": { "type": "string", "format": "at-uri" },
        "cid": { "type": "string", "format": "cid" },
        "author": { "type": "ref", "ref": "#authorView" },
        "record": { "type": "unknown" },
        "indexedAt": { "type": "string", "format": "datetime" }
      }
    },
    "authorView": {
      "type": "object",
      "required": ["did"],
      "properties": {
        "did": { "type": "string", "format": "did" },
        "handle": { "type": "string" }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.identity.resolveEnrollments",
  "defs": {
    "main": {
      "type": "query",
      "description": "Resolve enrollment boundaries for a DID. Returns the boundary domains the user is enrolled in.",
      "parameters": {
        "type": "params",
        "required": ["did"],
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID to resolve enrollment boundaries for."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["did", "enrolled", "boundaries"],
          "properties": {
            "did": {
              "type": "string",
              "format": "did"
            },
            "enrolled": {
              "type": "boolean",
              "description": "Whether the DID is enrolled in this Stratos service."
            },
            "boundaries": {
              "type": "array",
              "description": "Boundary domains the user is enrolled in. Empty if not enrolled.",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.repo.hydrateRecord",
  "defs": {
    "main": {
      "type": "query",
      "description": "Hydrate a single record by URI. Returns the record if viewer has boundary access.",
      "parameters": {
        "type": "params",
        "required": ["uri"],
        "properties": {
          "uri": {
            "type": "string",
            "format": "at-uri",
            "description": "The AT-URI of the record to hydrate"
          },
          "cid": {
            "type": "string",
            "format": "cid",
            "description": "Optional CID to verify record version"
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["uri", "cid", "value"],
          "properties": {
            "uri": {
              "type": "string",
              "format": "at-uri"
            },
            "cid": {
              "type": "string",
              "format": "cid"
            },
            "value": {
              "type": "unknown"
            }
          }
        }
      },
      "errors": [
        {
          "name": "RecordNotFound",
          "description": "The requested record does not exist"
        },
        {
          "name": "RecordBlocked",
          "description": "Access to the record is blocked due to boundary restrictions"
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.repo.hydrateRecords",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Hydrate multiple records by URI. Returns records filtered by viewer's boundary access.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["uris"],
          "properties": {
            "uris": {
              "type": "array",
              "description": "Array of AT-URIs to hydrate (max 100)",
              "items": {
                "type": "string",
                "format": "at-uri"
              },
              "maxLength": 100
            }
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["records", "notFound", "blocked"],
          "properties": {
            "records": {
              "type": "array",
              "description": "Successfully hydrated records",
              "items": {
                "type": "ref",
                "ref": "#recordView"
              }
            },
            "notFound": {
              "type": "array",
              "description": "URIs that were not found",
              "items": {
                "type": "string",
                "format": "at-uri"
              }
            },
            "blocked": {
              "type": "array",
              "description": "URIs blocked due to boundary restrictions",
              "items": {
                "type": "string",
                "format": "at-uri"
              }
            }
          }
        }
      }
    },
    "recordView": {
      "type": "object",
      "required": ["uri", "cid", "value"],
      "properties": {
        "uri": {
          "type": "string",
          "format": "at-uri"
        },
        "cid": {
          "type": "string",
          "format": "cid"
        },
        "value": {
          "type": "unknown"
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.repo.importRepo",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Import a repository from a CAR file. Verifies record CID integrity and re-signs with the destination service key. The caller must be enrolled as the DID in the CAR's commit block.",
      "input": {
        "encoding": "application/vnd.ipld.car"
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["imported"],
          "properties": {
            "imported": {
              "type": "integer",
              "description": "Number of records successfully imported."
            }
          }
        }
      },
      "errors": [
        {
          "name": "InvalidCar",
          "description": "The CAR file is malformed, has missing blocks, or contains records with mismatched CIDs."
        },
        {
          "name": "RepoAlreadyExists",
          "description": "The destination already has records for this DID. Import is only supported for empty repos."
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.repo.uploadBlob",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Upload a new blob, to be referenced from a Stratos repository record. The blob will be deleted if it is not referenced within a time window (eg, minutes). Blob restrictions (mimetype, size, etc) are enforced when the reference is created. Requires auth, implemented by Stratos service.",
      "input": {
        "encoding": "*/*"
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["blob"],
          "properties": {
            "blob": { "type": "blob" }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.server.listDomains",
  "defs": {
    "main": {
      "type": "query",
      "description": "Returns the list of boundary domains available on this Stratos service.",
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["domains"],
          "properties": {
            "domains": {
              "type": "array",
              "description": "The boundary domains available on this service.",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.space.getRecord",
  "defs": {
    "main": {
      "type": "query",
      "description": "Get a single record from a permissioned space. Spec-shaped mirror of com.atproto.space.getRecord (atproto#5187): callable with standard user auth (the caller must be a member of the space) or with a space credential for that space (for syncing services). The record must belong to the requested space; records outside it - including records with no space at all - resolve to RecordNotFound (no existence leak).",
      "parameters": {
        "type": "params",
        "required": ["space", "repo", "collection", "rkey"],
        "properties": {
          "space": {
            "type": "string",
            "description": "The space's at:// URI (at://{did}/space/{type}/{skey}). Its space DID must equal this service's DID."
          },
          "repo": {
            "type": "string",
            "format": "did",
            "description": "The DID of the account whose repo to read from."
          },
          "collection": {
            "type": "string",
            "format": "nsid",
            "description": "The NSID of the record collection."
          },
          "rkey": {
            "type": "string",
            "maxLength": 512,
            "description": "The Record Key."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["uri", "cid", "value"],
          "properties": {
            "uri": {
              "type": "string",
              "format": "at-uri"
            },
            "cid": {
              "type": "string",
              "format": "cid"
            },
            "value": {
              "type": "unknown"
            }
          }
        }
      },
      "errors": [
        {
          "name": "RecordNotFound",
          "description": "The record does not exist in the requested space (or does not exist at all - indistinguishable by design)."
        },
        {
          "name": "UnknownSpace",
          "description": "The requested space URI is malformed or its space DID does not match this service's DID."
        },
        {
          "name": "AuthRequired",
          "description": "The caller is not admitted to the requested space (not a member, or the presented credential targets a different space)."
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.space.getSpaceCredential",
  "defs": {
    "main": {
      "type": "procedure",
      "description": "Issue a space credential (JWT) for a space the caller is a member of. The credential is bearer-shaped and multi-use until it expires; it is signed by the space authority's signing key so any repo host can verify it without contacting the authority. Identity is resolved from a delegation token when provided, otherwise from the DPoP-authenticated user. Membership is checked live against the enrollment store. App-axis (client attestation) gating is enforced here: spaces configured with an app allow-list require a valid client attestation whose attested client_id is listed; spaces that are open ignore any attestation supplied.",
      "input": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["space"],
          "properties": {
            "space": {
              "type": "string",
              "description": "The space's at:// URI (at://{did}/space/{type}/{skey}). Its space DID must equal this service's DID."
            },
            "delegationToken": {
              "type": "string",
              "description": "Optional space-delegation JWT. When present, the caller's identity is taken from this token (its target space must equal `space`) instead of the DPoP session."
            },
            "clientAttestation": {
              "type": "string",
              "description": "Optional client-attestation JWT (an OAuth private_key_jwt client assertion to the space authority). Required only for spaces gated on client app identity (appAccess allowList); the allow-list is evaluated against the attested client_id. Ignored for open spaces."
            }
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["credential", "expiresAt"],
          "properties": {
            "credential": {
              "type": "string",
              "description": "The compact-serialized space-credential JWT."
            },
            "expiresAt": {
              "type": "string",
              "format": "datetime",
              "description": "The credential's expiry time (matches the JWT `exp` claim)."
            }
          }
        }
      },
      "errors": [
        {
          "name": "InvalidToken",
          "description": "The supplied delegation token failed verification, or its target space does not match the requested space."
        },
        {
          "name": "NotEnrolled",
          "description": "The identified user is not enrolled in the boundary corresponding to the requested space."
        },
        {
          "name": "UnknownSpace",
          "description": "The requested space URI is malformed or its space DID does not match this service's DID."
        },
        {
          "name": "AttestationRequired",
          "description": "The requested space gates on client app identity (appAccess allowList) but no valid client attestation was supplied."
        },
        {
          "name": "ClientNotAllowed",
          "description": "A valid client attestation was supplied but its attested client_id is not in the space's app allow-list."
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.sync.getBlob",
  "defs": {
    "main": {
      "type": "query",
      "description": "Get a blob by CID with boundary-based access control.",
      "parameters": {
        "type": "params",
        "required": ["did", "cid"],
        "properties": {
          "did": { "type": "string", "format": "did" },
          "cid": { "type": "string", "format": "cid" }
        }
      },
      "output": {
        "encoding": "*/*"
      },
      "errors": [{ "name": "BlobNotFound" }, { "name": "Forbidden" }]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.sync.getRepo",
  "defs": {
    "main": {
      "type": "query",
      "description": "Export the full repository as a CAR file. Returns all record blocks, MST nodes, and the signed commit.",
      "parameters": {
        "type": "params",
        "required": ["did"],
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID of the repo to export."
          },
          "since": {
            "type": "string",
            "format": "tid",
            "description": "Optional revision cursor. If provided, only blocks newer than this revision are included."
          }
        }
      },
      "output": {
        "encoding": "application/vnd.ipld.car"
      },
      "errors": [
        {
          "name": "RepoNotFound",
          "description": "The requested repo does not exist or has no commits."
        }
      ]
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.sync.listRecordPaths",
  "defs": {
    "main": {
      "type": "query",
      "description": "Full-state recovery: enumerate a repo's record paths and their current CIDs, mirroring listRecords semantics. Record values are inlined by default; excludeValues returns metadata only. Boundary-gated: the caller only observes records within its enrolled boundaries. Intended as the fallback when the oplog (listRepoOps) returns OplogTruncated: the caller enumerates paths, diffs locally, and fetches misses. Callers must authenticate with a signed service JWT via the Authorization: Bearer header.",
      "parameters": {
        "type": "params",
        "required": ["did"],
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID of the repo to enumerate."
          },
          "collection": {
            "type": "string",
            "format": "nsid",
            "description": "Optional single collection to enumerate. When omitted, all collections are enumerated."
          },
          "cursor": {
            "type": "string",
            "description": "Opaque pagination cursor from a previous response."
          },
          "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 1000,
            "default": 100,
            "description": "Maximum number of rows to return in this page."
          },
          "excludeValues": {
            "type": "boolean",
            "default": false,
            "description": "When true, record values are omitted and only path metadata is returned."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["records"],
          "properties": {
            "records": {
              "type": "array",
              "items": { "type": "ref", "ref": "#recordPath" },
              "description": "The record paths in this page."
            },
            "cursor": {
              "type": "string",
              "description": "Opaque pagination cursor to fetch the next page. Absent when enumeration is complete."
            }
          }
        }
      },
      "errors": [
        {
          "name": "RepoNotFound",
          "description": "The requested repo does not exist."
        },
        {
          "name": "AuthRequired",
          "description": "Service authentication is required."
        }
      ]
    },
    "recordPath": {
      "type": "object",
      "description": "A record path with its current CID and optionally its value.",
      "required": ["collection", "rkey", "cid"],
      "properties": {
        "collection": {
          "type": "string",
          "format": "nsid",
          "description": "The record collection."
        },
        "rkey": {
          "type": "string",
          "maxLength": 512,
          "description": "The record key."
        },
        "cid": {
          "type": "string",
          "format": "cid",
          "description": "The CID (string form) of the current record value."
        },
        "value": {
          "type": "unknown",
          "description": "The current record value, inlined by default. Omitted when excludeValues is true."
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.sync.listRepoOps",
  "defs": {
    "main": {
      "type": "query",
      "description": "Incremental pull sync of a repo's operation log (oplog), mirroring listRepoOps semantics. Returns record operations after the `since` revision, with current record values inlined by default. Boundary-gated: the caller only observes operations for records within its enrolled boundaries. When the response reaches the end of the available log AND no concurrent write is detected, `caughtUp` is true and the repo's current signed commit is included. A concurrent write instead yields `caughtUp` false with a cursor and no commit; that response can carry no operations and repeat the cursor you sent, so poll again on `caughtUp` false and do not read an unchanged cursor as a stall. Callers must authenticate with a signed service JWT via the Authorization: Bearer header. The oplog is a droppable transport optimization; if `since` predates retained history the OplogTruncated error is returned so the caller falls back to full-state recovery (listRecordPaths).",
      "parameters": {
        "type": "params",
        "required": ["did"],
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID of the repo to sync."
          },
          "since": {
            "type": "string",
            "format": "tid",
            "description": "A revision (TID). Only operations after this revision are returned. Omit to start from the beginning of retained history."
          },
          "limit": {
            "type": "integer",
            "minimum": 1,
            "maximum": 1000,
            "default": 100,
            "description": "Maximum number of operations to return in this page."
          },
          "cursor": {
            "type": "string",
            "description": "Opaque pagination cursor from a previous response."
          },
          "excludeValues": {
            "type": "boolean",
            "default": false,
            "description": "When true, record values are omitted and only operation metadata is returned."
          }
        }
      },
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["ops", "caughtUp"],
          "properties": {
            "ops": {
              "type": "array",
              "items": { "type": "ref", "ref": "#repoOp" },
              "description": "The operations in this page, in ascending revision order."
            },
            "cursor": {
              "type": "string",
              "description": "Opaque pagination cursor to fetch the next page. Absent when caughtUp is true. Can repeat the cursor you sent when a concurrent write was detected."
            },
            "caughtUp": {
              "type": "boolean",
              "description": "True when this response reached the end of the available log and no concurrent write was detected. When true, `commit` is present unless the repo has no commits yet. Never falsely true: a write landing during the request yields false, and under continuous writes it may stay false indefinitely."
            },
            "commit": {
              "type": "ref",
              "ref": "#signedCommit",
              "description": "The repo's current signed MST commit. Present when caughtUp is true, EXCEPT for a repo with no commits yet (no writes) - in that case there is nothing to sign and also no ops to sync."
            }
          }
        }
      },
      "errors": [
        {
          "name": "OplogTruncated",
          "description": "The requested `since` revision falls outside retained history: it predates the oldest retained event (compacted), postdates the newest (not a rev this repo issued), or there is no retained log to check it against. The caller must fall back to full-state recovery."
        },
        {
          "name": "RepoNotFound",
          "description": "The requested repo does not exist."
        },
        {
          "name": "AuthRequired",
          "description": "Service authentication is required."
        }
      ]
    },
    "repoOp": {
      "type": "object",
      "description": "A single record operation in the oplog. `cid` null means delete; `prev` null means create.",
      "required": ["rev", "collection", "rkey"],
      "properties": {
        "rev": {
          "type": "string",
          "format": "tid",
          "description": "The revision of the commit that produced this operation. Atomic multi-writes share one rev."
        },
        "collection": {
          "type": "string",
          "format": "nsid",
          "description": "The record collection."
        },
        "rkey": {
          "type": "string",
          "maxLength": 512,
          "description": "The record key."
        },
        "cid": {
          "type": "string",
          "format": "cid",
          "description": "The CID (string form) of the current record value. Null (absent) for a delete."
        },
        "prev": {
          "type": "string",
          "format": "cid",
          "description": "The CID (string form) of the record value this operation superseded. Null (absent) for a create."
        },
        "value": {
          "type": "unknown",
          "description": "The current record value, inlined by default for create/update ops. Omitted when excludeValues is true or for a delete."
        }
      }
    },
    "signedCommit": {
      "type": "object",
      "description": "A signed MST v3 commit, as persisted (read verbatim, not re-signed).",
      "required": ["did", "version", "data", "rev", "sig"],
      "properties": {
        "did": {
          "type": "string",
          "format": "did",
          "description": "The DID of the repo."
        },
        "version": {
          "type": "integer",
          "description": "The commit version (3)."
        },
        "data": {
          "type": "string",
          "format": "cid",
          "description": "The CID (string form) of the MST root node."
        },
        "rev": {
          "type": "string",
          "format": "tid",
          "description": "The commit revision."
        },
        "prev": {
          "type": "string",
          "format": "cid",
          "description": "The CID (string form) of the previous commit. Absent for the first commit."
        },
        "sig": {
          "type": "string",
          "description": "The commit signature, base64-encoded (the exact persisted bytes)."
        }
      }
    }
  }
},
{
  "lexicon": 1,
  "id": "zone.stratos.sync.subscribeRecords",
  "defs": {
    "main": {
      "type": "subscription",
      "description": "Subscribe to stratos events. When 'did' is provided, subscribes to record updates for that account. When omitted, subscribes to service-level events (enrollments). Callers must authenticate with a signed service JWT via the Authorization: Bearer header.",
      "parameters": {
        "type": "params",
        "properties": {
          "did": {
            "type": "string",
            "format": "did",
            "description": "The DID of the account to subscribe to. If omitted, subscribes to service-level enrollment events."
          },
          "cursor": {
            "type": "integer",
            "description": "The last known event sequence number to resume from."
          },
          "domain": {
            "type": "string",
            "maxLength": 253,
            "description": "Optional domain filter. Only events for records with this domain in their boundary will be emitted."
          }
        }
      },
      "message": {
        "schema": {
          "type": "union",
          "refs": ["#commit", "#enrollment", "#info"]
        }
      },
      "errors": [
        { "name": "FutureCursor", "description": "Cursor is in the future." },
        { "name": "AuthRequired", "description": "Authentication is required." }
      ]
    },
    "commit": {
      "type": "object",
      "description": "A commit event containing record operations.",
      "required": ["seq", "did", "time", "rev", "ops"],
      "properties": {
        "seq": {
          "type": "integer",
          "description": "The sequence number of this event."
        },
        "did": {
          "type": "string",
          "format": "did",
          "description": "The DID of the account."
        },
        "time": {
          "type": "string",
          "format": "datetime",
          "description": "Timestamp of when the event was sequenced."
        },
        "rev": {
          "type": "string",
          "format": "tid",
          "description": "The repo revision."
        },
        "ops": {
          "type": "array",
          "items": { "type": "ref", "ref": "#recordOp" },
          "description": "List of record operations in this commit."
        }
      }
    },
    "recordOp": {
      "type": "object",
      "description": "A single record operation within a commit.",
      "required": ["action", "path"],
      "properties": {
        "action": {
          "type": "string",
          "knownValues": ["create", "update", "delete"],
          "maxLength": 32,
          "description": "The type of operation."
        },
        "path": {
          "type": "string",
          "maxLength": 512,
          "description": "The record path (collection/rkey)."
        },
        "cid": {
          "type": "cid-link",
          "description": "The CID of the record. Present for create and update operations."
        },
        "record": {
          "type": "unknown",
          "description": "The record content. Present for create and update operations."
        }
      }
    },
    "info": {
      "type": "object",
      "description": "An informational message about the subscription state.",
      "required": ["name"],
      "properties": {
        "name": {
          "type": "string",
          "knownValues": ["OutdatedCursor"],
          "maxLength": 128,
          "description": "The type of info message."
        },
        "message": {
          "type": "string",
          "maxLength": 1024,
          "description": "Additional details about the info message."
        }
      }
    },
    "enrollment": {
      "type": "object",
      "description": "An enrollment event indicating a user has enrolled or unenrolled from the service.",
      "required": ["did", "action", "time"],
      "properties": {
        "did": {
          "type": "string",
          "format": "did",
          "description": "The DID of the user."
        },
        "action": {
          "type": "string",
          "knownValues": ["enroll", "unenroll"],
          "maxLength": 32,
          "description": "The enrollment action."
        },
        "service": {
          "type": "string",
          "format": "uri",
          "description": "The Stratos service endpoint URL."
        },
        "boundaries": {
          "type": "array",
          "items": { "type": "string" },
          "description": "The boundaries assigned to the user."
        },
        "time": {
          "type": "string",
          "format": "datetime",
          "description": "Timestamp of the enrollment event."
        }
      }
    }
  }
},
] as unknown as LexiconDoc[]
