packages:
  - 'stratos-core'
  - 'stratos-service'
  - 'stratos-client'
  - 'stratos-indexer'
  - 'stratos-feedgen'
  - 'webapp'
allowBuilds:
  core-js: true
  cpu-features: true
  esbuild: true
  ngrok: true
  protobufjs: true
  sharp: true
  ssh2: true
