import { writeFileSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const packageJsonPath = resolve(scriptDirectory, '..', 'package.json')
const { version } = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))

const content = `\
/*
 * This file is generated by scripts/generate-version.ts. Do not edit it manually.
 */
export const VERSION = '${version}'
`

writeFileSync(join(scriptDirectory, '..', 'src', 'version.ts'), content)
